language: r
dist: focal
latex: false
pandoc: false

cache:
  packages: yes
  directories:
    - $HOME/bin

env:
  global:
    - PATH=$HOME/bin:$PATH

before_script:
  - Rscript -e "blogdown::install_hugo('0.74.3')"
  - hugo version

script:
  - hugo
  - ./_deploy.sh
