language: c
dist: focal

cache:
  directories:
    - $HOME/bin

env:
  global:
    - PATH=$HOME/bin:$PATH

install:
  - "[ -x ~/bin/hugo ] || curl -sL https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.tar.gz | tar zxf - && mv hugo ~/bin"
  - hugo version

script:
  - git clean -f
  - hugo
  - ./_deploy.sh
